'''
Created on Feb 14, 2012

@author: Leonardo Zuniga S
'''
from google.appengine.ext import db

# This is an extensible class with all the parameter definitions present in the JSON files
class loansModel(db.Expando):
    customer_account_key = db.StringProperty(name="customer_account_key",verbose_name="MO Name",required=True)
    collateral_key = db.IntegerProperty(name="collateral_key",verbose_name="Loan Number",required=True)
    borr_1_last_name = db.StringProperty(name="borr_1_last_name",verbose_name="Last Name (Primary Borrower)",required=True)
    borr_1_first_name = db.StringProperty(name="borr_1_first_name",verbose_name="First Name (Primary Borrower)")
    borr_2_last_name = db.StringProperty(name="borr_2_last_name",verbose_name="Last Name (Secondary Borrower)")
    borr_2_first_name = db.StringProperty(name="borr_2_first_name",verbose_name="First Name (Secondary Borrower)")
    address = db.StringProperty(name="address",verbose_name="Property address")
    city = db.StringProperty(name="city",verbose_name="Property city",required=True)
    state = db.StringProperty(name="state",verbose_name="Property state",required=True)
    pzip = db.StringProperty(name="zip",verbose_name="Property zip",required=True)
    ss_number = db.IntegerProperty(name="ss_number",verbose_name="SS# (Primary Borrower)",required=True)
    ss_number_2 = db.IntegerProperty(name="ss_number_2",verbose_name="SS# (Secondary Borrower)")
    citizenship_flag = db.BooleanProperty(name="citizenship_flag",verbose_name="Citizen Y/N",required=True)
    product_code = db.StringProperty(name="product_code",verbose_name="Loan Type",required=True)
    orig_upb = db.IntegerProperty(name="orig_upb",verbose_name="Original Unpaid Balance",required=True)
    curr_upb = db.IntegerProperty(name="curr_upb",verbose_name="Current Unpaid Balance",required=True)
    orig_p_i = db.FloatProperty(name="orig_p_i",verbose_name="Original Principal & Interest Payment",required=True)
    orig_rate = db.FloatProperty(name="orig_rate",verbose_name="Original Interest Rate",required=True)
    origination_date = db.DateProperty(name="origination_date",verbose_name="origination date",required=True)
    effective_date = db.DateProperty(name="effective_date",verbose_name="Request Date",required=True)
    firstdue = db.DateProperty(name="firstdue",verbose_name="first payment due date",required=True, default="2/1/2012")
    maturity = db.DateProperty(name="maturity",verbose_name="maturity date",required=True)
    is_adjustable = db.BooleanProperty(name="is_adjustable",verbose_name="is interest rate adjustable?",required=True)
    advance_amt = db.IntegerProperty(name="advance_amt",verbose_name="MO advance amount",required=True)
    funding_amount = db.FloatProperty(name="funding_amount",verbose_name="Amount Sent")
    funding_method_code = db.IntegerProperty(name="funding_method_code",verbose_name="funding method code",required=True, default=1)
    funding_id = db.IntegerProperty(name="funding_id",verbose_name="funding id")
    payee1_name = db.StringProperty(name="payee1_name",verbose_name="1st Payee Name",required=True)
    payee1_address = db.StringProperty(name="payee1_address",verbose_name="1st Payee Address")
    payee1_city = db.StringProperty(name="payee1_city",verbose_name="1st Payee City",required=True)
    payee1_state = db.StringProperty(name="payee1_state",verbose_name="1st Payee State",required=True)
    payee1_zip = db.StringProperty(name="payee1_zip",verbose_name="1st Payee Zip",required=True)
    payee1_accountnum = db.StringProperty(name="payee1_accountnum",verbose_name="1st payee account number")
    payee1_abanum = db.StringProperty(name="payee1_abanum",verbose_name="1st payee ABA number")
    payee1_instruction1 = db.StringProperty(name="payee1_instruction1",verbose_name="1st Payee Wire Instruction 1")
    payee1_instruction2 = db.StringProperty(name="payee1_instruction2",verbose_name="1st Payee Wire Instruction 2")
    payee2_name = db.StringProperty(name="payee2_name",verbose_name="2nd Payee Name")
    payee2_address = db.StringProperty(name="payee2_address",verbose_name="2nd Payee Address")
    payee2_city = db.StringProperty(name="payee2_city",verbose_name="2nd Payee City")
    payee2_state = db.StringProperty(name="payee2_state",verbose_name="2nd Payee State")
    payee2_zip = db.StringProperty(name="payee2_zip",verbose_name="2nd Payee Zip")
    payee2_accountnum = db.StringProperty(name="payee2_accountnum",verbose_name="2nd payee account number")
    payee2_abanum = db.StringProperty(name="payee2_abanum",verbose_name="2nd payee ABA number")
    payee2_instruction1 = db.StringProperty(name="payee2_instruction1",verbose_name="2nd Payee Wire Instruction 1")
    payee2_instruction2 = db.StringProperty(name="payee2_instruction2",verbose_name="2nd Payee Wire Instruction 2")
    investor_code = db.StringProperty(name="investor_code",verbose_name="investor code",required=True)
    inv_commit_number = db.IntegerProperty(name="inv_commit_number",verbose_name="Investor Commitment Number",required=True)
    inv_commit_price = db.IntegerProperty(name="inv_commit_price",verbose_name="Investor Commitment Price",required=True, default=100)
    inv_commit_date = db.DateProperty(name="inv_commit_date",verbose_name="Investor Commitment Date",required=True)
    inv_commit_expire_date = db.DateProperty(name="inv_commit_expire_date",verbose_name="Investor Commitment Expire Date",required=True)
    investor_id = db.StringProperty(name="investor_id",verbose_name="investor id")
    property_type_code = db.StringProperty(name="property_type_code",verbose_name="property type code",required=True)
    lien_position = db.IntegerProperty(name="lien_position",verbose_name="lien position",required=True)
    original_ltv = db.FloatProperty(name="original_ltv",verbose_name="original ltv",required=True)
    original_cltv = db.FloatProperty(name="original_cltv",verbose_name="original cltv",required=True)
    mtg_ins_pct = db.BooleanProperty(name="mtg_ins_pct",verbose_name="Mortgage Insurance",required=True, default=0)
    fico_score = db.IntegerProperty(name="fico_score",verbose_name="fico score",required=True)
    original_term = db.IntegerProperty(name="original_term",verbose_name="original term",required=True)
    amortization_term = db.IntegerProperty(name="amortization_term",verbose_name="amortization term",required=True)
    purpose_code = db.StringProperty(name="purpose_code",verbose_name="purpose code",required=True)
    units = db.IntegerProperty(name="units",verbose_name="units",required=True, default=1)
    orig_appraised_value = db.IntegerProperty(name="orig_appraised_value",verbose_name="original appraised value",required=True)
    appraiser_name = db.StringProperty(name="appraiser_name",verbose_name="appraiser name",required=True)
    occupancy_code = db.StringProperty(name="occupancy_code",verbose_name="occupancy code",required=True)
    doc_level_code = db.IntegerProperty(name="doc_level_code",verbose_name="Document Level Code",required=True)
    debt_service_ratio = db.FloatProperty(name="debt_service_ratio",verbose_name="debt service ratio",required=True)
    is_escrow_required = db.BooleanProperty(name="is_escrow_required",verbose_name="is escrow required?",required=True)
    armmargin = db.IntegerProperty(name="armmargin",verbose_name="ARM Margin",required=True)
    armindex = db.StringProperty(name="armindex",verbose_name="ARM Index")
    armteaser = db.FloatProperty(name="armteaser",verbose_name="ARM Teaser")
    first_rate_change_date = db.DateProperty(name="first_rate_change_date",verbose_name="first rate change date")
    anncap_init = db.IntegerProperty(name="anncap_init",verbose_name="Initial Rate Adjustment Cap")
    rate_change_frequency = db.IntegerProperty(name="rate_change_frequency",verbose_name="rate adjustment frequency")
    armpcap = db.IntegerProperty(name="armpcap",verbose_name="Periodic Rate Adjustment Cap")
    armlcap = db.IntegerProperty(name="armlcap",verbose_name="Lifetime Rate Adjustment Cap")
    armlfloor = db.FloatProperty(name="armlfloor",verbose_name="Lifetime Floor Rate")
    purchase_price = db.IntegerProperty(name="purchase_price",verbose_name="purchase price",required=True)
    prepay_penalty_flag = db.BooleanProperty(name="prepay_penalty_flag",verbose_name="prepayment penalty flag",required=True, default=False)
    prepay_penalty_pct = db.FloatProperty(name="prepay_penalty_pct",verbose_name="prepayment penalty percentage",required=True, default=0)
    prepay_period = db.StringProperty(name="prepay_period",verbose_name="prepayment period")
    interest_only_flag = db.BooleanProperty(name="interest_only_flag",verbose_name="interest only flag",required=True, default=False)
    interest_only_period = db.IntegerProperty(name="interest_only_period",verbose_name="interest only  period",required=True, default=0)
    paid_to_date = db.DateProperty(name="paid_to_date",verbose_name="paid to date",required=True, default="1/1/2012")
    is_assets_verified = db.BooleanProperty(name="is_assets_verified",verbose_name="Assets verified?",required=True, default=True)
    times_delinquent_30 = db.IntegerProperty(name="times_delinquent_30",verbose_name="times delinquent 30",required=True, default=0)
    times_delinquent_60 = db.IntegerProperty(name="times_delinquent_60",verbose_name="times delinquent 60",required=True, default=0)
    times_delinquent_90 = db.IntegerProperty(name="times_delinquent_90",verbose_name="times delinquent 90",required=True, default=0)
    times_delinquent_120 = db.IntegerProperty(name="times_delinquent_120",verbose_name="times delinquent 120",required=True, default=0)
    borr_1_employ_flag = db.BooleanProperty(name="borr_1_employ_flag",verbose_name="Primary borrower employment flag",required=True)
    borr_2_employ_flag = db.BooleanProperty(name="borr_2_employ_flag",verbose_name="Secondary Borrower employment flag",required=True)
    borr_1_marital_status = db.StringProperty(name="borr_1_marital_status",verbose_name="Primary borrower marital status",required=True)
    borr_2_marital_status = db.StringProperty(name="borr_2_marital_status",verbose_name="Secondary borrower marital status")
    borr_1_age = db.IntegerProperty(name="borr_1_age",verbose_name="Primary borrower age",required=True)
    borr_2_age = db.IntegerProperty(name="borr_2_age",verbose_name="Secondary borrower age")
    borr_1_gender = db.StringProperty(name="borr_1_gender",verbose_name="Primary borrower Gender", choices=set(["M","F"]))
    borr_2_gender = db.StringProperty(name="borr_2_gender",verbose_name="Secondary borrower gender", choices=set(["M","F"]))
    is_first_time_buyer = db.BooleanProperty(name="is_first_time_buyer",verbose_name="is first time buyer?",required=True, default=False)
    is_negam = db.BooleanProperty(name="is_negam",verbose_name="is loan negatively amortizing?",required=True, default=False)
    armoption = db.BooleanProperty(name="armoption",verbose_name="is loan an Option ARM?",required=True, default=False)
    first_delinquent_date = db.DateProperty(name="first_delinquent_date",verbose_name="first delinquent date")
    bankruptcy_chapter = db.StringProperty(name="bankruptcy_chapter",verbose_name="bankruptcy chapter")
    bankruptcy_discharge_date = db.DateProperty(name="bankruptcy_discharge_date",verbose_name="bankruptcy discharge date")
    foreclosure_satisfied_date = db.DateProperty(name="foreclosure_satisfied_date",verbose_name="foreclosure satisfied date")
    prepay_enforceability = db.StringProperty(name="prepay_enforceability",verbose_name="prepay enforceability")
    du_response = db.StringProperty(name="du_response",verbose_name="du response",required=True)
    du_case_number = db.IntegerProperty(name="du_case_number",verbose_name="du case number",required=True, default="1000100100")
    max_negam = db.FloatProperty(name="max_negam",verbose_name="maximum negatively amortization",required=True, default=0)
    first_rate_adjust_period = db.IntegerProperty(name="first_rate_adjust_period",verbose_name="first rate adjustment period")
    tradelines = db.IntegerProperty(name="tradelines",verbose_name="tradelines",required=True)
    reserved_term = db.IntegerProperty(name="reserved_term",verbose_name="reserved term",required=True)
    reserved_amt = db.FloatProperty(name="reserved_amt",verbose_name="reserved amount",required=True)
    mers_min = db.StringProperty(name="mers_min",verbose_name="mers min number",required=True, default="100000000000000000")
    mtg_ins_company = db.StringProperty(name="mtg_ins_company",verbose_name="mortgage insurance company")
    servicing_fee = db.FloatProperty(name="Servicing_fee",verbose_name="Servicing fee",required=True, default=0)
    servicer = db.StringProperty(name="Servicer",verbose_name="Servicer")
    cur_note_rate = db.FloatProperty(name="Cur_note_rate",verbose_name="Current note rate",required=True)
    armpfloor = db.IntegerProperty(name="Armpfloor",verbose_name="Periodic Rate Cap")
    initial_recast_period = db.IntegerProperty(name="Initial_recast_period",verbose_name="Initial recast period")
    subsequent_recast_period = db.IntegerProperty(name="subsequent_recast_period",verbose_name="subsequent recast period")
    teaser_period = db.IntegerProperty(name="teaser_period",verbose_name="teaser period")
    is_balloon = db.BooleanProperty(name="Is_balloon",verbose_name="Is loan a balloon?",required=True, default=False)
    market_value_cap = db.IntegerProperty(name="Market_value_cap",verbose_name="Market value cap",required=True, default=100)
    fha_case_number = db.StringProperty(name="FHA_Case_Number",verbose_name="FHA Case Number")
    max_rate = db.FloatProperty(name="Max_Rate",verbose_name="Max Rate")
    is_lpmi = db.BooleanProperty(name="Is_LPMI",verbose_name="Is LPMI",required=True, default=False)
    lpmi_pct = db.FloatProperty(name="LPMI_PCT",verbose_name="LPMI Percentage",required=True, default=False)
    junior_lien_amount = db.IntegerProperty(name="Junior_lien_amount",verbose_name="Junior lien amount",required=True, default=0)
    loan_type = db.StringProperty(name="Loan_Type",verbose_name="Loan Type",required=True)
    interest_only_end_date = db.DateProperty(name="Interest_Only_End_Date",verbose_name="Interest Only End Date")
    first_payment_change_date = db.DateProperty(name="First_payment_change_date",verbose_name="First payment change date")
    look_back_period = db.IntegerProperty(name="Look_back_period",verbose_name="Look back period")
    interest_rounding_feature = db.StringProperty(name="Interest_rounding_feature",verbose_name="Interest rounding feature")
    interest_rounding_percentage = db.FloatProperty(name="Interest_rounding_percentage",verbose_name="Interest rounding percentage")
    first_adj_max_initial_rate = db.FloatProperty(name="1st_adj_max_initial_rate",verbose_name="1st adjustment maximum initial rate")
    first_adj_min_initial_rate = db.FloatProperty(name="1st_adj_min_initial_rate",verbose_name="1st adjustment minimum initial rate")
    corelogic_fraud_risk_score = db.IntegerProperty(name="CoreLogic Fraud Risk Score",verbose_name="CoreLogic Fraud Risk Score",required=True)
    corelogic_collateral_risk_score = db.IntegerProperty(name="CoreLogic Collateral Risk Score",verbose_name="CoreLogic Collateral Risk Score",required=True)
    loan_officer = db.StringProperty(name="Loan Officer",verbose_name="Loan Officer",required=True)
    nmls_n = db.IntegerProperty(name="NMLS #",verbose_name="NMLS #",required=True)
    u_w = db.StringProperty(name="U/W",verbose_name="Loan Underwriter",required=True)
    mo_city = db.StringProperty(name="MO City",verbose_name="MO City",required=True)
    mo_state = db.StringProperty(name="MO State",verbose_name="MO State")
    mo_zip = db.StringProperty(name="MO Zip",verbose_name="MO Zip")
